import { useState, useCallback } from 'react';

interface DailyRecordData {
  date: string;
  weight?: number;
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
  exerciseTime: number;
  exerciseBurned: number;
  exercises: Array<{
    type: string;
    duration: number;
    displayName?: string;
  }>;
  meals: Array<{
    name: string;
    calories: number;
    time?: string;
  }>;
}

interface SecureShareData {
  userId: string; // ユーザー識別用ハッシュ
  timestamp: number; // データ生成時刻
  expiresAt: number; // 有効期限
  sessionId: string; // セッション識別子
  data: DailyRecordData; // 実際のデータ
}

export function useShareRecord() {
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Canvas で画像生成（基本的なデザイン）
  const generateImage = useCallback((recordData: DailyRecordData): Promise<Blob> => {
    return new Promise((resolve, reject) => {
      try {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        
        if (!ctx) {
          throw new Error('Canvas context not available');
        }
        
        // 画像サイズ (Instagram Stories: 1080x1920, 一般的な共有: 1200x630)
        canvas.width = 600;
        canvas.height = 800;
        
        // 背景
        const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height);
        gradient.addColorStop(0, '#ff6b6b');
        gradient.addColorStop(1, '#ffa726');
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        
        // メインタイトル
        ctx.fillStyle = 'white';
        ctx.font = 'bold 32px sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText('ヘルシーくん記録', canvas.width / 2, 80);
        
        // 日付
        ctx.font = '24px sans-serif';
        ctx.fillText(recordData.date, canvas.width / 2, 120);
        
        // 記録カード背景（角丸）
        ctx.fillStyle = 'rgba(255, 255, 255, 0.9)';
        const drawRoundRect = (x: number, y: number, w: number, h: number, r: number) => {
          ctx.beginPath();
          ctx.moveTo(x + r, y);
          ctx.lineTo(x + w - r, y);
          ctx.quadraticCurveTo(x + w, y, x + w, y + r);
          ctx.lineTo(x + w, y + h - r);
          ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
          ctx.lineTo(x + r, y + h);
          ctx.quadraticCurveTo(x, y + h, x, y + h - r);
          ctx.lineTo(x, y + r);
          ctx.quadraticCurveTo(x, y, x + r, y);
          ctx.closePath();
        };
        
        drawRoundRect(40, 150, canvas.width - 80, 500, 20);
        ctx.fill();
        
        // テキスト色
        ctx.fillStyle = '#333';
        ctx.textAlign = 'left';
        
        let yPos = 200;
        
        // カロリー情報
        ctx.font = 'bold 24px sans-serif';
        ctx.fillText('🔥 カロリー', 80, yPos);
        ctx.font = '20px sans-serif';
        ctx.fillText(`${recordData.calories}kcal`, 80, yPos + 30);
        yPos += 70;
        
        // PFC情報
        ctx.font = 'bold 24px sans-serif';
        ctx.fillText('🍖 栄養バランス', 80, yPos);
        ctx.font = '18px sans-serif';
        ctx.fillText(`P: ${recordData.protein}g`, 80, yPos + 30);
        ctx.fillText(`F: ${recordData.fat}g`, 240, yPos + 30);
        ctx.fillText(`C: ${recordData.carbs}g`, 400, yPos + 30);
        yPos += 70;
        
        // 体重情報
        if (recordData.weight) {
          ctx.font = 'bold 24px sans-serif';
          ctx.fillText('⚖️ 体重', 80, yPos);
          ctx.font = '20px sans-serif';
          ctx.fillText(`${recordData.weight}kg`, 80, yPos + 30);
          yPos += 70;
        }
        
        // 運動情報
        ctx.font = 'bold 24px sans-serif';
        ctx.fillText('💪 運動', 80, yPos);
        if (recordData.exerciseTime > 0) {
          ctx.font = '20px sans-serif';
          ctx.fillText(`${recordData.exerciseTime}分`, 80, yPos + 30);
          
          // 運動詳細（最大3つまで）
          recordData.exercises.slice(0, 3).forEach((exercise, index) => {
            ctx.font = '16px sans-serif';
            ctx.fillText(`• ${exercise.displayName || exercise.type}`, 80, yPos + 60 + (index * 25));
          });
        } else {
          ctx.font = '18px sans-serif';
          ctx.fillText('運動記録なし', 80, yPos + 30);
        }
        
        // フッター
        ctx.fillStyle = 'white';
        ctx.font = '16px sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText('Generated by ヘルシーくん', canvas.width / 2, canvas.height - 30);
        
        // Blob に変換
        canvas.toBlob((blob) => {
          if (blob) {
            resolve(blob);
          } else {
            reject(new Error('Failed to generate image blob'));
          }
        }, 'image/png', 0.9);
        
      } catch (error) {
        reject(error);
      }
    });
  }, []);
  
  // 記録データを取得してフォーマット
  const formatRecordData = useCallback((
    selectedDate: Date,
    mealData: any,
    exerciseData: any[],
    weightData: any
  ): DailyRecordData => {
    const dateString = selectedDate.toLocaleDateString('ja-JP');
    
    // 食事データ集計
    const allMeals: any[] = [];
    const mealTypes = ['breakfast', 'lunch', 'dinner', 'snack'];
    
    mealTypes.forEach(type => {
      if (mealData[type] && Array.isArray(mealData[type])) {
        mealData[type].forEach((meal: any) => {
          allMeals.push({
            name: meal.name || '不明',
            calories: meal.calories || 0,
            time: meal.time
          });
        });
      }
    });
    
    // 食事データから正しくPFC計算
    let totalCalories = 0;
    let totalProtein = 0;
    let totalFat = 0;
    let totalCarbs = 0;
    
    mealTypes.forEach(type => {
      if (mealData[type] && Array.isArray(mealData[type])) {
        mealData[type].forEach((meal: any) => {
          totalCalories += meal.calories || 0;
          totalProtein += meal.protein || 0;
          totalFat += meal.fat || 0;
          totalCarbs += meal.carbs || 0;
        });
      }
    });
    
    // 運動データ集計
    console.log('🔍 運動データフィルタリング開始:', {
      selectedDate,
      targetDate: selectedDate.toLocaleDateString('sv-SE'),
      exerciseDataLength: exerciseData.length,
      allExercises: exerciseData.map(ex => ({
        date: ex.date,
        formattedDate: new Date(ex.date).toLocaleDateString('sv-SE'),
        duration: ex.duration,
        caloriesBurned: ex.caloriesBurned
      }))
    });
    
    const todayExercises = exerciseData.filter(exercise => {
      // 日本時間ベースで日付比較（他のフックと同じ）
      const targetDateStr = selectedDate.toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' });
      
      let matches = false;
      
      // 運動データは日付プロパティを持っていない場合が多いので、他の方法で判定
      // 1. exercise.dateがある場合
      if (exercise.date) {
        const exerciseDate = exercise.date;
        
        if (typeof exerciseDate === 'string') {
          matches = exerciseDate === targetDateStr;
          
          if (!matches) {
            const normalizedDate = new Date(exerciseDate).toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' });
            matches = normalizedDate === targetDateStr;
          }
        } else if (exerciseDate instanceof Date) {
          matches = exerciseDate.toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' }) === targetDateStr;
        }
      }
      // 2. timestampがある場合
      else if (exercise.timestamp) {
        const timestampDate = new Date(exercise.timestamp);
        matches = timestampDate.toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' }) === targetDateStr;
      }
      // 3. 日付情報がない場合は今日とみなす（当日入力の運動）
      else {
        const today = new Date().toLocaleDateString('sv-SE', { timeZone: 'Asia/Tokyo' });
        matches = targetDateStr === today;
      }
      
      console.log(`🔍 運動データ比較:`, {
        exerciseId: exercise.id,
        exerciseName: exercise.name,
        exerciseDate: exercise.date,
        exerciseTimestamp: exercise.timestamp,
        targetDate: targetDateStr,
        matches,
        exercise: { duration: exercise.duration, calories: exercise.calories }
      });
      
      return matches;
    });
    
    const totalExerciseTime = todayExercises.reduce((sum, exercise) => {
      // duration（時間） がない場合は 0 で計算（強度系運動は時間ベースでない）
      return sum + (exercise.duration || 0);
    }, 0);
    
    // 消費カロリー計算（運動データから）
    const totalBurnedCalories = todayExercises.reduce((sum, exercise) => {
      const caloriesBurned = exercise.caloriesBurned || 0;
      const calories = exercise.calories || 0;
      const finalCalories = caloriesBurned || calories;
      
      console.log('🔍 個別運動カロリー詳細:', {
        exerciseName: exercise.name,
        caloriesBurned: caloriesBurned,
        calories: calories,
        finalCalories: finalCalories,
        notes: exercise.notes,
        timestamp: exercise.timestamp
      });
      
      return sum + finalCalories;
    }, 0);
    
    console.log('🔍 運動集計結果:', {
      todayExercisesCount: todayExercises.length,
      totalExerciseTime,
      totalBurnedCalories,
      todayExerciseDetails: todayExercises.map(ex => ({
        name: ex.name,
        duration: ex.duration,
        calories: ex.calories,
        caloriesBurned: ex.caloriesBurned,
        notes: ex.notes,
        timestamp: ex.timestamp
      }))
    });
    
    // 体重データ（現在の実装に合わせて調整）
    const todayWeight = weightData?.current ? { weight: weightData.current } : undefined;
    
    const result = {
      date: dateString,
      weight: todayWeight?.weight,
      calories: Math.round(totalCalories),
      protein: Math.round(totalProtein * 10) / 10,
      fat: Math.round(totalFat * 10) / 10,
      carbs: Math.round(totalCarbs * 10) / 10,
      exerciseTime: totalExerciseTime,
      exerciseBurned: totalBurnedCalories,
      exercises: todayExercises.map(ex => ({
        type: ex.type || ex.name || '運動',
        duration: ex.duration || 0,
        displayName: ex.displayName || ex.name || ex.type || '運動'
      })),
      meals: allMeals
    };
    
    return result;
  }, []);
  
  // 共有実行
  const shareRecord = useCallback(async (recordData: DailyRecordData) => {
    try {
      setIsGenerating(true);
      
      // 画像生成
      const imageBlob = await generateImage(recordData);
      const imageFile = new File([imageBlob], `healthy-record-${recordData.date}.png`, { 
        type: 'image/png' 
      });
      
      // Web Share API が利用可能かチェック
      if (navigator.canShare && navigator.canShare({ files: [imageFile] })) {
        await navigator.share({
          files: [imageFile],
          title: `ヘルシーくん記録 - ${recordData.date}`,
          text: `${recordData.date}の記録\n🔥 ${recordData.calories}kcal\n💪 ${recordData.exerciseTime}分運動`
        });
        return { success: true, method: 'web-share-api' };
      }
      
      // LIFF Share Target Picker (LINE) - 一時的に無効化（画像アップロード未実装）
      // if (typeof window !== 'undefined' && window.liff) {
      //   try {
      //     const imageUrl = await uploadImageForLIFF(imageBlob);
      //     await window.liff.shareTargetPicker([{
      //       type: "image",
      //       originalContentUrl: imageUrl,
      //       previewImageUrl: imageUrl
      //     }]);
      //     return { success: true, method: 'liff-share' };
      //   } catch (liffError) {
      //     console.error('LIFF share failed:', liffError);
      //   }
      // }
      
      // フォールバック: ダウンロード
      return downloadImage(imageBlob, recordData.date);
      
    } catch (error) {
      console.error('Share failed:', error);
      return { success: false, error: error.message };
    } finally {
      setIsGenerating(false);
    }
  }, [generateImage]);
  
  // 画像をアップロードしてURL取得（簡易版・後で改良）
  const uploadImageForLIFF = async (blob: Blob): Promise<string> => {
    // 一時的にObjectURLを返す（本格実装時は外部ストレージにアップロード）
    return URL.createObjectURL(blob);
  };
  
  // 画像ダウンロード
  const downloadImage = (blob: Blob, date: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `healthy-record-${date.replace(/\//g, '-')}.png`;
    a.click();
    URL.revokeObjectURL(url);
    return { success: true, method: 'download' };
  };
  
  return {
    isGenerating,
    shareRecord,
    formatRecordData,
    generateImage
  };
}